version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_roulette
    command:
      -p 5432
    expose:
      - 5432
    env_file:
      - .env-prod

  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: roulette
    command: [ "/roulette/app.sh" ]
    ports:
      - 5555:8000
    depends_on:
      - db
