"""empty message

Revision ID: 03be9fbb2ef3
Revises: 04544ead332b
Create Date: 2023-09-10 16:54:53.279837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03be9fbb2ef3'
down_revision = '04544ead332b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
