"""empty message

Revision ID: 041ae0c06114
Revises: ea8010b85aa5
Create Date: 2023-09-10 17:36:53.244879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041ae0c06114'
down_revision = 'ea8010b85aa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
