"""Initial

Revision ID: 04544ead332b
Revises: 
Create Date: 2023-09-10 01:18:18.433377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import table

revision = '04544ead332b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    cell = table('cells',
                sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
                sa.Column('cell', sa.String(), nullable=True),
                sa.Column('weight', sa.Integer(), nullable=True),
                )
    op.bulk_insert(cell,
                   [
                       {'id': 1, 'weight': 20},
                       {'id': 2, 'weight': 100},
                       {'id': 3, 'weight': 45},
                       {'id': 4, 'weight': 70},
                       {'id': 5, 'weight': 15},
                       {'id': 6, 'weight': 140},
                       {'id': 7, 'weight': 20},
                       {'id': 8, 'weight': 20},
                       {'id': 9, 'weight': 140},
                       {'id': 10, 'weight': 45},
                   ])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('users')
    op.drop_table('cells')
    # ### end Alembic commands ###
