"""empty message

Revision ID: 7e6af16aba26
Revises: 03be9fbb2ef3
Create Date: 2023-09-10 17:00:09.656989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6af16aba26'
down_revision = '03be9fbb2ef3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
