"""empty message

Revision ID: d2412c279e14
Revises: 7e6af16aba26
Create Date: 2023-09-10 17:07:05.801338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2412c279e14'
down_revision = '7e6af16aba26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
