"""empty message

Revision ID: ea8010b85aa5
Revises: 45a519fbdd87
Create Date: 2023-09-10 17:17:50.781875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8010b85aa5'
down_revision = '45a519fbdd87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
