"""empty message

Revision ID: fcedd337efa3
Revises: d2412c279e14
Create Date: 2023-09-10 17:12:04.841147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcedd337efa3'
down_revision = 'd2412c279e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('round_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'round_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('round_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('logs', 'round_id')
    # ### end Alembic commands ###
